### ISSUE TITLE
Việt hoá máy quét

### ISSUE THREAD

**Issue by nguyenvantamcntt95** [Belmont-Gabriel/MIUI8-XML-Vietnamese#1]
App máy quét không được việt hoá do app máy quét đã đổi tên thành MiuiScanner.apk, anh check lại gói ngôn ngữ và đổi tên với việt hoá lại vì máy quét có nhiều tính năng mới. Cảm ơn anh đã đọc.

**Comment by Belmont-Gabriel** [comment]
OK
