### ISSUE TITLE
Add collaborator

### ISSUE THREAD

**Issue by ingbrzy** [Belmont-Gabriel/MIUI8-XML-Vietnamese#3]
Please add @MarkH-UK as collaborator for write access... thanks

**Comment by ingbrzy** [comment]
Please add @MarkH-UK as collaborator... thanks

**Comment by ingbrzy** [comment]
Your issues will be fixed automatically if you add him...
http://translators.xiaomi.eu/XML_MIUI8-Vietnamese-vi.html

**Comment by ingbrzy** [comment]
@Belmont-Gabriel

**Comment by Belmont-Gabriel** [comment]
Sorry for reply late.
I addded him. Thank @ingbrzy
