### ISSUE TITLE
Text message missing letter

### ISSUE THREAD

**Issue by chethetlc** [Belmont-Gabriel/MIUI8-XML-Vietnamese#4]
If my text message includes some special letters, like ứ, ắ, ờ,... the text the receiver gets will replace these letters with a space. 
for example, if I send a message "thắng", the receiver gets the message "th ng".
this error seems to appear in recent weekly releases. Please fix it. thank you.

**Comment by ingbrzy** [comment]
Disable GSM alphabet in SMS settings...
